"""add clients and used_jtis tables

Revision ID: 4fab8467497f
Revises: a477083c5329
Create Date: 2026-08-22 10:08:02.370470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fab8467497f'
down_revision: Union[str, Sequence[str], None] = 'a477083c5329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('public_jwk', sa.JSON(), nullable=False),
    sa.Column('redirect_uris', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('used_jtis',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('used_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('used_jtis')
    op.drop_table('clients')
    # ### end Alembic commands ###
