"""Generates a JWS signing keypair for the test client and registers its
public JWK in the clients table, under the same client_id as the CN on the
mTLS cert generated by generate_certs.sh — that's what ties the two identity
mechanisms (mTLS and JWS) together. Re-running replaces the registration."""

import json
from pathlib import Path

from coreledger.client_sdk import generate_signing_keypair, register_client_jwk
from coreledger.db.session import SessionLocal

CLIENT_ID = "coreledger-test-client"  # must match nginx/certs client cert CN
REDIRECT_URI = "https://localhost:8443/oauth/callback"  # doesn't need to be live for the demo
DEV_KEYS_DIR = Path(__file__).resolve().parent.parent / "dev_keys"


def main() -> None:
    DEV_KEYS_DIR.mkdir(exist_ok=True)
    key = generate_signing_keypair()

    private_path = DEV_KEYS_DIR / "client_signing_key.json"
    private_path.write_text(json.dumps(key.as_dict(private=True)))
    print(f"private signing key written to {private_path}")

    with SessionLocal() as session:
        register_client_jwk(
            session,
            client_id=CLIENT_ID,
            public_jwk=key.as_dict(private=False),
            redirect_uris=[REDIRECT_URI],
        )

    print(f"registered client_id={CLIENT_ID} with public JWK")


if __name__ == "__main__":
    main()
